services:
    netgen_layouts.sylius.controller.base:
        class: Netgen\Bundle\LayoutsSyliusBundle\Controller\Admin\Controller
        abstract: true
        calls:
            - setContainer: ["@Psr\\Container\\ContainerInterface"]
            - checkPermissions: []

    netgen_layouts.sylius.controller.connect_component:
        class: Netgen\Bundle\LayoutsSyliusBundle\Controller\Admin\ConnectComponent
        parent: netgen_layouts.sylius.controller.base
        arguments:
            - "@netgen_layouts.api.service.block"
            - "@netgen_layouts.sylius.repository.component"
        tags:
            - { name: container.service_subscriber }
            - { name: controller.service_arguments }
