services:
    netgen_layouts.sylius.layout_resolver.target_type.product:
        class: Netgen\Layouts\Sylius\Layout\Resolver\TargetType\Product
        tags:
            - { name: netgen_layouts.target_type, priority: 170 }

    netgen_layouts.sylius.layout_resolver.target_type.form_mapper.product:
        class: Netgen\Layouts\Sylius\Layout\Resolver\Form\TargetType\Mapper\Product
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: sylius_product }

    netgen_layouts.sylius.layout_resolver.target_handler.doctrine.sylius_product:
        class: Netgen\Layouts\Sylius\Layout\Resolver\TargetHandler\Doctrine\Product
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: sylius_product }

    netgen_layouts.sylius.layout_resolver.target_type.taxon_product:
        class: Netgen\Layouts\Sylius\Layout\Resolver\TargetType\TaxonProduct
        tags:
            - { name: netgen_layouts.target_type, priority: 160 }

    netgen_layouts.sylius.layout_resolver.target_type.form_mapper.taxon_product:
        class: Netgen\Layouts\Sylius\Layout\Resolver\Form\TargetType\Mapper\TaxonProduct
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: sylius_taxon_product }

    netgen_layouts.sylius.layout_resolver.target_handler.doctrine.sylius_taxon_product:
        class: Netgen\Layouts\Sylius\Layout\Resolver\TargetHandler\Doctrine\TaxonProduct
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: sylius_taxon_product }

    netgen_layouts.sylius.layout_resolver.target_type.taxon:
        class: Netgen\Layouts\Sylius\Layout\Resolver\TargetType\Taxon
        tags:
            - { name: netgen_layouts.target_type, priority: 150 }

    netgen_layouts.sylius.layout_resolver.target_type.form_mapper.taxon:
        class: Netgen\Layouts\Sylius\Layout\Resolver\Form\TargetType\Mapper\Taxon
        tags:
            - { name: netgen_layouts.target_type.form_mapper, target_type: sylius_taxon }

    netgen_layouts.sylius.layout_resolver.target_handler.doctrine.sylius_taxon:
        class: Netgen\Layouts\Sylius\Layout\Resolver\TargetHandler\Doctrine\Taxon
        tags:
            - { name: netgen_layouts.target_type.doctrine_handler, target_type: sylius_taxon }

    netgen_layouts.sylius.layout_resolver.condition_type.channel:
        class: Netgen\Layouts\Sylius\Layout\Resolver\ConditionType\Channel
        arguments:
            - "@sylius.context.channel"
        tags:
            - { name: netgen_layouts.condition_type }

    netgen_layouts.sylius.layout_resolver.condition_type.form_mapper.channel:
        class: Netgen\Layouts\Sylius\Layout\Resolver\Form\ConditionType\Mapper\Channel
        arguments:
            - "@sylius.repository.channel"
        tags:
            - { name: netgen_layouts.condition_type.form_mapper, condition_type: sylius_channel }

    netgen_layouts.sylius.layout_resolver.condition_type.locale:
        class: Netgen\Layouts\Sylius\Layout\Resolver\ConditionType\Locale
        tags:
            - { name: netgen_layouts.condition_type }

    netgen_layouts.sylius.layout_resolver.condition_type.form_mapper.locale:
        class: Netgen\Layouts\Sylius\Layout\Resolver\Form\ConditionType\Mapper\Locale
        arguments:
            - "@sylius.repository.locale"
        tags:
            - { name: netgen_layouts.condition_type.form_mapper, condition_type: sylius_locale }
