services:
    netgen_layouts.sylius.locale.provider:
        class: Netgen\Layouts\Sylius\Locale\LocaleProvider
        decorates: netgen_layouts.locale.provider
        arguments:
            - "@sylius.provider.locale"
