services:
    netgen_layouts.sylius.templating.twig.extension.sylius:
        class: Netgen\Bundle\LayoutsSyliusBundle\Templating\Twig\Extension\SyliusExtension
        tags:
            - { name: twig.extension }

    netgen_layouts.sylius.templating.twig.runtime.sylius:
        class: Netgen\Bundle\LayoutsSyliusBundle\Templating\Twig\Runtime\SyliusRuntime
        arguments:
            - "@sylius.repository.product"
            - "@sylius.repository.taxon"
            - "@sylius.repository.channel"
            - "@sylius.repository.locale"
            - "%netgen_layouts.sylius.component_create_routes%"
            - "%netgen_layouts.sylius.component_update_routes%"
        tags:
            - { name: twig.runtime }
