services:
    netgen_layouts.sylius.validator.product:
        class: Netgen\Layouts\Sylius\Validator\ProductValidator
        arguments:
            - "@sylius.repository.product"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_product }

    netgen_layouts.sylius.validator.taxon:
        class: Netgen\Layouts\Sylius\Validator\TaxonValidator
        arguments:
            - "@sylius.repository.taxon"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_taxon }

    netgen_layouts.sylius.validator.channel:
        class: Netgen\Layouts\Sylius\Validator\ChannelValidator
        arguments:
            - "@sylius.repository.channel"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_channel }

    netgen_layouts.sylius.validator.locale:
        class: Netgen\Layouts\Sylius\Validator\LocaleValidator
        arguments:
            - "@sylius.repository.locale"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_locale }

    netgen_layouts.sylius.validator.resource_type:
        class: Netgen\Layouts\Sylius\Validator\ResourceTypeValidator
        arguments:
            - "%netgen_layouts.sylius.condition.resource_types%"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_resource_type }

    netgen_layouts.sylius.validator.page:
        class: Netgen\Layouts\Sylius\Validator\PageValidator
        arguments:
            - "%netgen_layouts.sylius.target.pages%"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_page }

    netgen_layouts.sylius.validator.component:
        class: Netgen\Layouts\Sylius\Validator\ComponentValidator
        arguments:
            - "@netgen_layouts.sylius.component_repository"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_component }
