services:
    netgen_layouts.sylius.validator.product:
        class: Netgen\Layouts\Sylius\Validator\ProductValidator
        arguments:
            - "@sylius.repository.product"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_product }

    netgen_layouts.sylius.validator.taxon:
        class: Netgen\Layouts\Sylius\Validator\TaxonValidator
        arguments:
            - "@sylius.repository.taxon"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_taxon }

    netgen_layouts.sylius.validator.channel:
        class: Netgen\Layouts\Sylius\Validator\ChannelValidator
        arguments:
            - "@sylius.repository.channel"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_channel }

    netgen_layouts.sylius.validator.locale:
        class: Netgen\Layouts\Sylius\Validator\LocaleValidator
        arguments:
            - "@netgen_layouts.locale.provider"
        tags:
            - { name: validator.constraint_validator, alias: nglayouts_sylius_locale }
