nglayouts_sylius_admin_connect_component:
    path: /nglayouts/admin/sylius/blocks/{blockId}/{locale}/connect-component/{componentIdentifier}/{componentId}
    controller: netgen_layouts.sylius.controller.connect_component
    methods: [POST]
    requirements:
        componentId: \d+
    defaults:
        _nglayouts_status: draft
