events:
    sylius.shop.layout.stylesheets:
        blocks:
            netgen_layouts: '@NetgenLayouts/stylesheets.html.twig'
            netgen_layouts_standard:
                template: '@NetgenLayoutsStandard/stylesheets.html.twig'
                context:
                    full: true

    sylius.shop.layout.javascripts:
        blocks:
            netgen_layouts: '@NetgenLayouts/javascripts.html.twig'
            netgen_layouts_standard:
                template: '@NetgenLayoutsStandard/javascripts.html.twig'
                context:
                    full: true

    sylius.admin.layout.stylesheets:
        blocks:
            layouts_sylius_meta:
                template: "@NetgenLayoutsSylius/admin/nglayouts/meta.html.twig"

    sylius.admin.layout.javascripts:
        blocks:
            layouts_sylius_javascripts:
                template: "@NetgenLayoutsSylius/admin/nglayouts/javascripts.html.twig"
